task:
  id: multilabelclassification

  val_metrics: 
  - id: MultiLabelAveragePrecision
    average: micro
  - id: MultiLabelAveragePrecision
    average: macro


train_dataset:
  id: geobench.m-bigearthnet
  split: train
  subset: 0.10
  transform: ${_default_augms.train_augm}

val_dataset:
  id: geobench.m-bigearthnet
  split: val
  display_name: m-bigearthnet
  transform: ${_default_augms.test_augm}

test_datasets_list:
- id: geobench.m-bigearthnet
  split: test
  display_name: test
  transform: ${_default_augms.test_augm}


optim:
  epochs: 50
  save_checkpoint_frequency_epoch: 10
  eval_period_epoch: 100

  dl:
    batch_size: 400
    num_workers: 16
    persistent_workers: true