task:
  id: classification

  val_metrics:
  - id: MulticlassAccuracy
    top_k: 1
    average: micro
  - id: MulticlassAccuracy
    top_k: 1
    average: macro


train_dataset:
  id: resisc45
  root: ${oc.env:RDIR}/datasets/resisc45
  split: train
  transform: ${_default_augms.train_augm}

val_dataset:
  id: resisc45
  root: ${oc.env:RDIR}/datasets/resisc45
  split: val
  subset: 0.1
  transform: ${_default_augms.train_augm}

test_dataset:
  id: resisc45
  root: ${oc.env:RDIR}/datasets/resisc45
  split: test
  transform: ${_default_augms.train_augm}

optim:
  epochs: 50
  save_checkpoint_frequency_epoch: 10
  eval_period_epoch: 10

  dl:
    batch_size: 200
    num_workers: 8
    persistent_workers: true
